#!/usr/bin/env bash
# sandbox-boot — full-stack cold boot from a fresh git checkout.
#
# After a sandbox restart ONLY the git repo survives (node_modules, .env.local,
# .data, global tools are wiped). This script rebuilds everything offline:
#
#   1. pnpm install (scripts off — ffmpeg-static's postinstall host is blocked)
#   2. Prisma offline kit (vendored WASM engines + adapter-pg catalog patch)
#   3. .env.local
#   4. PostgreSQL 17 (embedded binaries from the npm registry) + Redis (vendored)
#   5. prisma generate + db push (WASM schema engine, zero downloads)
#   6. offline footage clips (deterministic ffmpeg renders)
#   7. production builds (turbo)
#
# Then start the services (see sandbox-services.sh) and import footage +
# regenerate the demo campaign.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

echo "══ 1/7 dependencies ══════════════════════════════════════════"
command -v pnpm >/dev/null 2>&1 || npm install -g pnpm@latest
pnpm install --prefer-offline --ignore-scripts

echo "══ 2/7 prisma offline kit ════════════════════════════════════"
node infra/scripts/offline-prisma.mjs

echo "══ 3/7 .env.local ════════════════════════════════════════════"
if [ ! -f .env.local ]; then
  cat > .env.local <<'EOF'
# Local persistent environment — written by infra/scripts/sandbox-boot.sh (never commit)
DATABASE_URL=postgresql://aca:aca_dev_pw@127.0.0.1:5433/autocreator
REDIS_URL=redis://127.0.0.1:6379
AUTH_JWT_SECRET=dev-only-insecure-local-secret-change-me-0123456789abcdef
ACA_LOCAL_GENERATION=1
ACA_STORAGE_DIR=/home/user/auto-publisher-ai/.data/aca-storage
KMS_KEY_ID=dev-key-1
PORT=4000
EOF
  echo "  ✓ written"
else
  echo "  ✓ exists"
fi

echo "══ 4/7 data plane (postgres + redis) ═════════════════════════"
bash infra/scripts/local-postgres.sh start
bash infra/scripts/local-redis.sh start

echo "══ 5/7 database schema ═══════════════════════════════════════"
( cd packages/database && npx prisma generate && npx prisma db push )

echo "══ 6/7 offline footage clips ═════════════════════════════════"
bash infra/scripts/gen-footage.sh

echo "══ 7/7 production builds ═════════════════════════════════════"
pnpm exec turbo run build

cat <<'EOF'

✅ BOOT COMPLETE — start the services:

  bash infra/scripts/sandbox-services.sh start

(the owner account is auto-seeded on API boot; the demo campaign is
regenerated by the services script once the API answers /health)
EOF
